### PR TITLE
[pricing]: adjust the FAQ spacing for mobile.

### LINKED ISSUE #357: [pricing]: adjust the spacing for the FAQs on mobile.
On mobile, the padding needs to be adjusted

image

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #357

### CODE REVIEW

**Review by ChristinFrohne — CHANGES_REQUESTED** [review]
On Safari and Chrome the arrows are underneath the text. According to the mockup they should be in the same row as the text.

IMG_6256


**Sidenote:** How do I scale image in issues? This image is huge. Sorry about that 😬

**Comment by mikenikles** [comment]
@ChristinFrohne I fixed the arrow location on iOS. Could you please have a quick look at https://deploy-preview-358--gitpod-kumquat.netlify.app/pricing?

I don't think you can scale down an image unless you do it before you upload it. If you want, you can hide it like I do below, but I'd say don't bother and paste large images instead 😄 .

<details>
  <summary>Click to see image</summary>

pricing-ios
</details>

The code you'd need for the above to work is:

```
<details>
  <summary>Click to see image</summary>

![pricing-ios](https://user-images.githubusercontent.com/788827/114435058-bd189480-9b91-11eb-85bb-a33fc35d1ab6.jpeg)
</details>
```

**Comment by ChristinFrohne** [comment]
Thanks for the explanation @mikenikles 
The FAQ looks a lot better now. Tiny issue: the text could have an earlier break to keep more spacing for the arrows. 

IMG_6260

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have changed it so that the text wraps to the next line earlier. Please merge if the change looks good to you. Thanks

**Review by ChristinFrohne — APPROVED** [review]
Looks great now 🎉

**Pull request merged**
